### PR TITLE
Adding drush alias files.

### PR DESCRIPTION
**Pull request by AlannaBurke**
Adding the generated drush alias files.

### CODE REVIEW

**Comment by tobybellwood** [comment]
This won't be needed now that we have the new alias system in place?

The amazeeio/drupal_integrations package contains a wildcard alias and a drush command `drush la` to list all available aliases, without relying on the stub.

**Comment by AlannaBurke** [comment]
Welp, my build is failing and i forgot to commit these after i generated them, so ... they seem needed? (And i need this to work so I can do the video)

**Comment by AlannaBurke** [comment]
And yup, this PR succeeded, so that worked

**Comment by AlannaBurke** [comment]
I'm going to go ahead and merge this - we can get rid of this master branch after I'm done with the video - i just need something working to do this video!

**Pull request merged**
